/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { SettingsPage } from '../components/settings-page'
import type { BillingSettings } from '../types'
import {
  BILLING_DEFAULT_SECTION,
  getBillingSectionContent,
} from './section-registry.tsx'

const defaultBillingSettings: BillingSettings = {
  QuotaForNewUser: 0,
  PreConsumedQuota: 0,
  QuotaForInviter: 0,
  QuotaForInvitee: 0,
  TopUpLink: '',
  'general_setting.docs_link': '',
  'quota_setting.enable_free_model_pre_consume': true,
  QuotaPerUnit: 500000,
  USDExchangeRate: 7,
  'general_setting.quota_display_type': 'USD',
  'general_setting.custom_currency_symbol': '¤',
  'general_setting.custom_currency_exchange_rate': 1,
  DisplayInCurrencyEnabled: true,
  DisplayTokenStatEnabled: true,
  ModelPrice: '',
  ModelRatio: '',
  CacheRatio: '',
  CreateCacheRatio: '',
  CompletionRatio: '',
  ImageRatio: '',
  AudioRatio: '',
  AudioCompletionRatio: '',
  ExposeRatioEnabled: false,
  'billing_setting.billing_mode': '{}',
  'billing_setting.billing_expr': '{}',
  'tool_price_setting.prices': '{}',
  TopupGroupRatio: '',
  GroupRatio: '',
  UserUsableGroups: '',
  GroupGroupRatio: '',
  AutoGroups: '',
  DefaultUseAutoGroup: false,
  'group_ratio_setting.group_special_usable_group': '{}',
  PayAddress: '',
  EpayId: '',
  EpayKey: '',
  Price: 7.3,
  MinTopUp: 1,
  CustomCallbackAddress: '',
  PayMethods: '',
  AlipayEnabled: false,
  AlipaySandbox: false,
  AlipayAppId: '',
  AlipayPrivateKey: '',
  AlipayPublicKey: '',
  AlipayUnitPrice: 7.3,
  AlipayMinTopUp: 1,
  AlipayReturnUrl: '',
  AlipayNotifyUrl: '',
  WechatPayEnabled: false,
  WechatPaySandbox: false,
  WechatPayAppId: '',
  WechatPayMchId: '',
  WechatPayMerchantSerialNo: '',
  WechatPayMerchantPrivateKey: '',
  WechatPayAPIv3Key: '',
  WechatPayPlatformSerialNo: '',
  WechatPayPlatformPublicKey: '',
  WechatPayUnitPrice: 7.3,
  WechatPayMinTopUp: 1,
  WechatPayNotifyUrl: '',
  'payment_setting.amount_options': '',
  'payment_setting.amount_discount': '',
  'payment_setting.default_user_topup_discount': 1,
  'payment_setting.default_vvip_topup_discount': 1,
  'payment_setting.vip_activation_price': 1680,
  'payment_setting.vip_activation_commission_level1_amount': 1000,
  'payment_setting.vip_activation_commission_level2_amount': 400,
  'payment_setting.commission_min_withdraw_amount': 0,
  'payment_setting.compliance_confirmed': false,
  'payment_setting.compliance_terms_version': '',
  'payment_setting.compliance_confirmed_at': 0,
  'payment_setting.compliance_confirmed_by': 0,
  'payment_setting.compliance_confirmed_ip': '',
  StripeApiSecret: '',
  StripeWebhookSecret: '',
  StripePriceId: '',
  StripeUnitPrice: 8.0,
  StripeMinTopUp: 1,
  StripePromotionCodesEnabled: false,
  CreemApiKey: '',
  CreemWebhookSecret: '',
  CreemTestMode: false,
  CreemProducts: '[]',
  WaffoEnabled: false,
  WaffoApiKey: '',
  WaffoPrivateKey: '',
  WaffoPublicCert: '',
  WaffoSandboxPublicCert: '',
  WaffoSandboxApiKey: '',
  WaffoSandboxPrivateKey: '',
  WaffoSandbox: false,
  WaffoMerchantId: '',
  WaffoCurrency: 'USD',
  WaffoUnitPrice: 1,
  WaffoMinTopUp: 1,
  WaffoNotifyUrl: '',
  WaffoReturnUrl: '',
  WaffoPayMethods: '[]',
  WaffoPancakeEnabled: false,
  WaffoPancakeSandbox: false,
  WaffoPancakeMerchantID: '',
  WaffoPancakePrivateKey: '',
  WaffoPancakeWebhookPublicKey: '',
  WaffoPancakeWebhookTestKey: '',
  WaffoPancakeStoreID: '',
  WaffoPancakeProductID: '',
  WaffoPancakeReturnURL: '',
  WaffoPancakeCurrency: 'USD',
  WaffoPancakeUnitPrice: 1,
  WaffoPancakeMinTopUp: 1,
  'piggy_withdraw_setting.enabled': false,
  'piggy_withdraw_setting.domain': 'https://saas.xzsz.ltd',
  'piggy_withdraw_setting.app_key': '',
  'piggy_withdraw_setting.app_secret': '',
  'piggy_withdraw_setting.aes_iv': '0000000000000000',
  'piggy_withdraw_setting.tax_fund_id': '',
  'piggy_withdraw_setting.position_name': '',
  'piggy_withdraw_setting.position': '',
  'piggy_withdraw_setting.sign_jump_page': '',
  'piggy_withdraw_setting.sign_notify_url': '',
  'piggy_withdraw_setting.pay_notify_url': '',
  'piggy_withdraw_setting.request_timeout': 15,
  'piggy_withdraw_setting.callback_lock_ttl': 300,
  'piggy_withdraw_setting.cooldown_minutes': 30,
  'piggy_withdraw_setting.forbidden_withdraw_time': '',
  'piggy_withdraw_setting.calc_type': 'C',
  'piggy_withdraw_setting.platform_fee_rate': 8,
  'piggy_withdraw_setting.bank_remark': '',
  'qiniu_key_setting.enabled': false,
  'qiniu_key_setting.base_url': 'https://api.qnaigc.com',
  'qiniu_key_setting.child_account_base_url': 'https://api.qiniu.com',
  'qiniu_key_setting.access_key': '',
  'qiniu_key_setting.secret_key': '',
  'qiniu_key_setting.request_timeout': 15,
  'qiniu_key_setting.retry_interval_seconds': 300,
  'qiniu_key_setting.official_ledger_enabled': false,
  'qiniu_key_setting.official_ledger_cutover_time': 0,
  'qiniu_key_setting.official_ledger_sync_interval_seconds': 60,
  'qiniu_key_setting.official_ledger_window_hours': 6,
  'qiniu_key_setting.official_ledger_window_days': 2,
  'qiniu_key_setting.official_ledger_batch_size': 100,
  'qiniu_key_setting.official_ledger_rate_limit_per_second': 4,
  'qiniu_key_setting.official_ledger_retry_interval_seconds': 300,
  'qiniu_key_setting.cost_detail_cutover_time': 0,
  'qiniu_key_setting.cost_detail_lookback_days': 7,
  'qiniu_key_setting.cost_detail_auto_apply_enabled': true,
  'qiniu_key_setting.market_catalog_enabled': false,
  'qiniu_key_setting.market_catalog_base_url': 'https://openai.qiniu.com',
  'qiniu_key_setting.market_catalog_ttl_seconds': 3600,
  'qiniu_key_setting.market_catalog_overseas': true,
  'qiniu_key_setting.market_catalog_fallback_enabled': true,
  'qiniu_key_setting.child_account_email_domain': 'uk72.cn',
  'qiniu_key_setting.child_account_email_prefix': 'child',
  'qiniu_key_setting.child_account_password_length': 18,
  'qiniu_key_setting.child_account_request_timeout': 15,
  'qiniu_key_setting.child_account_retry_interval_seconds': 300,
  'qiniu_key_setting.child_account_binding_enabled': false,
  'qiniu_key_setting.child_account_assignment_mode': 'parent_only',
  'qiniu_key_setting.child_account_binding_cutover_time': 0,
  'checkin_setting.enabled': false,
  'checkin_setting.min_quota': 1000,
  'checkin_setting.max_quota': 10000,
}

export function BillingSettings() {
  return (
    <SettingsPage
      routePath='/_authenticated/system-settings/billing/$section'
      defaultSettings={defaultBillingSettings}
      defaultSection={BILLING_DEFAULT_SECTION}
      getSectionContent={getBillingSectionContent}
    />
  )
}
